python train.py \
    --dataroot  ../unfolding/unfolded \
    --display_id 0  \
    --csvA ../unfolding/csvs/test_external_cropped.csv \
    --csvB ../unfolding/csvs/train_cropped.csv \
    --phaseA test-set-external  \
    --phaseB train-val  \
    --batchSize 4 \
    --lr 0.00001 \
    --niter 25  \
    --no_html \
    --niter_decay 25 \
    --loadSize 256 \
    --fineSize 256 \
    --name uniklinik_external \
    --gpu_ids 0 \
    --model cycle_gan \
    --no_dropout \
    --epoch_len 42300 \
    --checkpoints_dir ./checkpoints/unnormalized
