python train.py \
    --dataroot $ENV_DATAROOT \
    --display_id 0  \
    --csvA $ENV_CSVA \
    --csvB $ENC_CCVB \
    --phaseA test-set-external  \
    --phaseB train-val  \
    --batchSize 4 \
    --lr 0.00001 \
    --niter 25  \
    --no_html \
    --niter_decay 25 \
    --loadSize 256 \
    --fineSize 256 \
    --resize_or_crop crop \
    --name $ENV_NAME \
    --gpu_ids 0 \
    --model cycle_gan \
    --no_dropout \
    --epoch_len 40000 \
    --checkpoints_dir $ENV_CHECKPOINT_DIR \
    --which_model_netG resnet_9blocks